name: Build and Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: |
          docker build -t my-ecommerce-app .

      - name: Tag Docker Image
        run: |
          docker tag my-ecommerce-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/my-ecommerce-app:latest

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/my-ecommerce-app:latest

      - name: Deploy to Elastic Beanstalk
        uses: aws-actions/aws-elastic-beanstalk-deploy@v1
        with:
          application-name: my-ecommerce-app
          environment-name: production
          version-label: ${{ github.sha }}
          region: us-east-2
          bucket-name: elasticbeanstalk-us-east-2-${{ secrets.AWS_ACCOUNT_ID }}