name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # - name: Create/Update CloudFormation Stack
      #   run: |
      #     aws cloudformation deploy \
      #       --template-file template.yml \
      #       --stack-name my-ecommerce-stack \
      #       --capabilities CAPABILITY_IAM \
      #       --parameter-overrides EnvironmentName=production \
      #       --region us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Tag Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t my-ecommerce-app .
          docker tag my-ecommerce-app:latest ${{ steps.login-ecr.outputs.registry }}/ecomm-app-repo:$IMAGE_TAG

      - name: Push Docker Image to ECR
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/my-ecommerce-app:${IMAGE_TAG}

      - name: Zip Application
        run: zip -r app.zip . -x "*.git*"

      - name: Upload to S3
        run: aws s3 cp app.zip s3://elasticbeanstalk-us-east-2-${{ secrets.AWS_ACCOUNT_ID }}/app-versions/app-${{ github.sha }}.zip

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name my-ecommerce-app \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket=elasticbeanstalk-us-east-2-${{ secrets.AWS_ACCOUNT_ID }},S3Key=app-versions/app-${{ github.sha }}.zip

          aws elasticbeanstalk update-environment \
            --application-name my-ecommerce-app \
            --environment-name production \
            --version-label ${{ github.sha }}
